### ISSUE TITLE
mathematical derivation of log likelihood and weight prior corresponding to code

### ISSUE THREAD

**Issue by hwfluid** [cics-nd/rans-uncertainty#15]
@NickGeneva Thank you for sharing the code. 

I am still very new to BNNs. When trying to understand the loss function, I could not match these code with the equations in the paper.

- For the likelihood, the code is
https://github.com/cics-nd/rans-uncertainty/blob/7d99fd906a1d73526ad041e6a9d705355f1c57c2/invar-nn/nn/foamSVGD.py#L138-L144
The mathematics should be (my understanding) 
![Snipaste_2021-01-28_23-39-38](https://user-images.githubusercontent.com/55072525/106161547-1c395080-61c2-11eb-8b14-95865ccfebec.png)

For the weight prior, the code is
https://github.com/cics-nd/rans-uncertainty/blob/7d99fd906a1d73526ad041e6a9d705355f1c57c2/invar-nn/nn/foamSVGD.py#L146-L151
Haven't figured out why Eq.(17) should be calculated in this way ?

Could you do a more specific explanation or mathematical derivation to help understand the above code, please ?

Best,

**Comment by NickGeneva** [comment]
Regarding the likelihood, you have made the assumption when taking the log that you can get rid of the normalizing factor (you call it a constant here). This is _not_ correct, since the variance (sigma in you equations, beta in the code) is not constant. Thus you must keep this factor in the log likelihood which will result in that additional term.

Regarding the prior, as explicitly stated in the paper following equation 17: "The resulting prior has the density of a narrow Student’s T -distribution centered at zero." Take the log of a Student T distribution and you will arrive at what is written in the code. This is even commented in the code as well with a [reference](https://github.com/cics-nd/rans-uncertainty/blob/master/invar-nn/nn/foamSVGD.py#L65).

Hope this clears things up.

**Comment by hwfluid** [comment]
Oh, thank you.
