### ISSUE TITLE
Wrong viscosity in square cylinder case

### ISSUE THREAD

**Issue by aiskhak** [cics-nd/rans-uncertainty#5]
Viscosity in training-data/square-cylinder/openfoam/constant/transportProperties

should be 0.0002
instead of 0.00002

Regards
Arsen

**Comment by aiskhak** [comment]
No, nu = 0.00002 is correct. The typo is in the original paper.
I am wondering, why my results for RANS are totally different from yours - I have turbulent wakes behind the cylinder (see the attached pictures for velocity)

I believe that the problem is with the inlet/outlet boundary conditions for epsilon, k, and nut. I use zeroGradient for all of them. What kind of BCs did you use?

Thanks

![Screenshot from 2020-10-07 13-19-41](https://user-images.githubusercontent.com/62344361/95365890-b4709a00-08a0-11eb-8b59-88c179a350c5.png)
![Screenshot from 2020-10-07 13-22-38](https://user-images.githubusercontent.com/62344361/95365893-b5093080-08a0-11eb-8168-158c9b356445.png)

**Comment by NickGeneva** [comment]
Hi Arsen,

Thanks for your patience. Regarding the viscosity.... as you discovered yes the viscosity in the file of 0.00002 is correct because the length scale of the mesh is 0.1. It is not a typo in the paper. For that table scaled the characteristic length of the square cylinder to 1 so the viscosity if of similar magnitude to the others (sorry about the confusion!).

For the boundary conditions you can find them in the provided data files. They have a lot of data in them because of the internal mesh so just search for "outlet" or "inlet" and you should find what I used.

Sometimes the vanilla RANS simulations can be a little unstable like this. I would also try adjusting your time-step size or other parameters in the simulation scheme. Been a while since I have ran RANS simulations so thats the best I can offer for now.

**Comment by aiskhak** [comment]
Thank you Nick. The problem that not all the BCs are printed in output files. The main concern is BCs for k, epsilon, and nut.
I obtained similar to your results with different BCs.

**Comment by NickGeneva** [comment]
My suggestion would be to use what works, I haven't touched RANS for a while so I do not remember completely what I did.

If adjusting the B.Cs such that the simulations is stable and the B.C. is still physically meaningful. I would use what you have that's working!

I do know I had some problems like this for some of the flows, which did require some tinkering with the parameters of the simulation. Seems like you've got it figured out.
